# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages, pkgs ? (import <nixpkgs> {}).pkgs }:
let
    inherit (haskellPackages) cabal cabalInstall ghc network attoparsec utf8String;
in cabal.mkDerivation (self: {
  pname = "hoax";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ network attoparsec utf8String ];
  buildTools = [ ghc cabalInstall pkgs.vim ];
  meta = {
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
